### ISSUE TITLE
Displays keybase information rather than the validator information

### ISSUE THREAD

**Issue by soc1c** [Colm3na/polkastats-v2#50]
ref #45 

my validators neither show the dothereum logo nor the dothereum name as provided in the pull request, rather, they display information from my private keybase account. is that intentional?

**Comment by mariopino** [comment]
Yes, sorry for the confusion, currently we pull the info from the keybase account.

By now can you change the logo and name in your keybase account and the info should gets updated automatically in 10 minutes or so.

I can change your validator info to other keybase account if you need to do so!

PD: To add that info is in the TODO list!
