### ISSUE TITLE
UX improvement for messages inside blocks with x

### ISSUE THREAD

**Issue by aitorjs** [Colm3na/polkastats-v2#78]
[screenshot](https://ibb.co/h1X3NJH)

All that info is interesting, but it is very annoying that it is shown in all menus and must be closed with the "X" continuously. We need a solution. To give some example solution: Create a section only for this info, get it to close only once for all menus (cookie?)...

**Comment by derfredy** [comment]
I'd suggest a new menu section for this info and remove it from the rest of pages.

**Comment by derfredy** [comment]
In our last meeting we decided to place the Statistical data in the home page only. There is no need of aditional menu for this purpose. We could access again home page clicking on the logo.
